/* 화상상담방 i18n (6개 언어) — page.jsx God 컴포넌트에서 분리(2026-06-21). 순수 데이터, 로직 0. */
export const COPY = {
  ko: {
    aiSubtitleDisclaimer: "AI 자막은 참고용입니다. 의학적 판단은 의료진과 직접 확인하세요.",
    // Guest join form
    guestTitle: "healwith 원격 상담",
    guestLede: "초대 링크로 입장합니다. 본인 이름을 입력하고 카메라/마이크 사용을 허용해주세요.",
    nameLabel: "이름 (의료진에게 표시됨)",
    namePlaceholder: "예: Айжан Нурланова / Ji-hoon Park",
    joining: "접속 중…",
    startConsult: "상담 시작",
    enterNameHint: "이름을 입력하면 입장할 수 있어요.",
    guestSecurity1: "🔒 통신은 AES-256으로 암호화됩니다. 이 링크는 이 상담 전용이에요 — 다른 사람에게 전달하지 마세요.",
    guestSecurity2: "녹화 / 녹음이 필요한 경우 의료진이 사전에 안내합니다.",
    // Validation / errors
    nameTooShort: "이름을 2자 이상 입력해주세요.",
    inviteExpired: "초대 링크가 만료되었거나 유효하지 않습니다. 관리자에게 새 링크를 요청하세요.",
    consultClosed: "이미 종료된 상담입니다.",
    rateLimited: "너무 많은 시도가 감지되어 차단됐습니다. 잠시 후 다시 시도해주세요.",
    connectFailed: "접속 실패",
    networkError: "네트워크 오류. 잠시 후 다시 시도해주세요.",
    // Loading / error states
    connecting: "상담 연결 중...",
    sessionNotFound: "상담 세션을 찾을 수 없습니다.",
    linkMissingInvite: "이 링크에는 입장권이 없어요. 링크를 보낸 분에게 「링크 복사」로 만든 새 초대 링크를 다시 받아주세요.",
    goBack: "돌아가기",
    // Session types
    sessionPre: "사전 상담",
    sessionFollowUp: "사후 관리",
    sessionEmergency: "긴급 상담",
    sessionDiagnostic: "진단 검토",
    consultationFallback: "Consultation",
    connected: "연결됨",
    reconnecting: "연결이 불안정해요 — 다시 연결 중…",
    tapToEnableAudio: "🔊 탭해서 소리 켜기",
    retryLabel: "다시 시도",
    noMediaNotice: "이 기기엔 카메라·마이크가 없어요. 듣기·보기로만 참여합니다.",
    mediaDeniedToast: "카메라·마이크 권한이 차단돼 있어요. 주소창 왼쪽 자물쇠(폰은 aA)에서 '허용'으로 바꾸고 새로고침하세요.",
    connectStuck: "연결에 실패했어요. 인터넷 상태를 확인하고 다시 시도해 주세요.",
    retryConnect: "다시 연결",
    connectNetworkTip: "회사·기관 인터넷은 영상통화를 막는 경우가 많아요. 휴대폰 핫스팟 등 다른 네트워크로 바꿔서 다시 시도해보세요.",
    preflightChecking: "네트워크에서 영상 연결이 되는지 확인 중…",
    preflightOk: "✅ 이 인터넷망에서는 통화가 됩니다 — 카메라·마이크는 위 미리보기로 확인하세요.",
    takenOverTitle: "다른 곳에서 입장했어요",
    takenOverBody: "같은 초대 링크로 다른 탭이나 기기에서 새로 입장해서, 이 화면의 연결은 종료됐어요. 통화는 새 화면에서 계속됩니다.",
    takenOverRejoin: "이 화면에서 다시 입장",
    micOffWarn: "마이크가 안 켜졌어요 — 지금은 상대가 목소리를 못 들어요.",
    micRetry: "마이크 켜기",
    waitingForOthers: "상대를 기다리는 중이에요… (아직 아무도 안 들어왔어요)",
    stillThereTitle: "아직 계신가요?",
    stillThereBody: "잠시 후 연결이 자동으로 끊어집니다. 계속 계시면 아래 버튼을 눌러주세요.",
    stillThereYes: "네, 있어요",
    idleClosedTitle: "연결을 끊었어요",
    idleClosedBody: "자리를 비우신 것 같아 연결만 끊었습니다. 상담은 그대로이니 언제든 다시 입장하세요.",
    idleRejoin: "다시 입장",
    cameraPreviewHint: "입장 전 카메라와 마이크를 확인하세요.",
    tabChat: "채팅",
    tabTranslation: "번역",
    cameraBlocked: "카메라·마이크 권한이 막혀 있어요. 브라우저 주소창의 자물쇠 아이콘에서 허용해주세요.",
    micMutedWarning: "마이크가 꺼져 있어요 — 말하는 중이라면 켜주세요",
    unpinLabel: "고정 해제",
    // Header controls
    stopTranslation: "번역 중지",
    startTranslation: "실시간 번역 시작",
    interpretation: "통역",
    captionsLabel: "자막",
    voiceLabel: "통역",
    voiceNotReady: "음성 통역이 아직 켜져 있지 않아요 (자막은 사용 가능)",
    voiceOnMsg: "음성 통역 켬 — 상대 목소리가 통역 음성으로 들려요",
    voiceOnPendingMsg: "음성 통역 켬 — 통역봇이 방에 들어오면 상대 목소리가 통역돼요",
    voiceUnavailableMsg: "통역 기능 준비 중이에요 — 자막(텍스트)은 그대로 쓸 수 있어요",
    // 통역봇이 «연결이 계속 실패한다»고 알릴 때 (2026-08-28 신설).
    // 예전엔 아무 표시가 없어 사용자가 「켜졌는데 왜 안 나오지」로 계속 기다렸다.
    voiceFailingMsg: "통역 연결이 끊겼어요 — 다시 잇는 중이에요. 자막(텍스트)은 그대로 쓸 수 있어요",
    voiceOffMsg: "음성 통역 끔 — 원래 목소리로 들려요",
    captionsOn: "자막 켜기",
    captionsOff: "자막 끄기",
    ctrlMic: "마이크",
    ctrlCam: "카메라",
    ctrlShare: "화면 공유",
    ctrlChat: "채팅",
    ctrlLang: "언어",
    ttsOff: "음성 출력 끄기",
    ttsOn: "음성 출력 켜기",
    subtitleSizeTitle: "자막 크기",
    subtitleSmall: "작게",
    subtitleMedium: "보통",
    subtitleLarge: "크게",
    endCall: "종료",
    // Admission states
    admissionRejectedTitle: "입장이 거절되었습니다",
    admissionRejectedBody: "의료진이 입장을 거절했습니다. 관리자 / 코디네이터에게 문의해주세요.",
    waitingRoomTitle: "대기실 (Waiting Room)",
    waitingRoomBody1: "의료진이 곧 입장을 승인합니다.",
    waitingRoomBody2: "잠시만 기다려주세요 — 이 화면은 자동으로 전환됩니다.",
    checkingStatus: "상태 확인 중...",
    waitingRoomPrivacy1: "이 대기실은 HIPAA / PIPA 기준 프라이버시 보호 대기실입니다.",
    waitingRoomPrivacy2: "진료 시작 전까지 카메라 / 마이크는 활성화되지 않습니다.",
    // Pending admissions banner (doctor)
    pendingWaiting: "입장 대기 중",
    anonymous: "익명",
    approve: "승인",
    reject: "거절",
    // Placeholder video tiles
    doctorTile: "Doctor (의사)",
    patientTile: "Patient (환자)",
    roleDoctor: "의사",
    rolePatient: "환자",
    roleCoordinator: "코디네이터",
    roleInterpreter: "통역",
    roleGuest: "참여자",
    speakerUnknown: "화자 미상",
    waiting: "대기 중...",
    myScreen: "내 화면",
    livekitDisabled: "LiveKit 미설정 — 화상 연결이 비활성화되었습니다. 채팅과 통번역은 사용 가능합니다.",
    // Chat panel
    chatEmpty: "상담 메시지가 여기에 표시됩니다.",
    messagePlaceholder: "메시지를 입력하세요...",
    // Translation panel
    translationEmpty1: "상단의 [통번역] 버튼을 눌러",
    translationEmpty2: "실시간 번역을 시작하세요.",
    sttUnsupported1: "이 브라우저는 음성 인식을 지원하지 않습니다.",
    sttUnsupported2: "음성이 안 되면 아래에 직접 입력해 번역하세요.",
    manualPlaceholder: "번역할 내용을 입력하세요...",
    manualHint: "마이크가 안 되는 환경이면 직접 입력해 번역할 수 있어요.",
    togglePanel: "채팅·번역 열기/닫기",
    sttFailedNotice: "이 브라우저에서는 음성 인식이 안 됩니다. 아래 입력칸으로 번역하세요.",
    myLangLabel: "내 언어",
    langMineLabel: "내 언어",
    langMineHint: "이 언어로 말하고 듣습니다. 상대의 말이 이 언어로 통역돼요.",
    langPartnerNote: "상대에게는 상대가 고른 언어로 전달됩니다 —",
    sameRoomTitle: "같은 공간에 다른 기기가 있는 것 같아요",
    sameRoomBody: "두 기기의 스피커와 마이크가 서로를 울려(하울링) 소리가 깨집니다. 이 기기를 화면 전용으로 바꾸면 사라져요.",
    sameRoomAction: "이 기기 소리 끄기",
    sameRoomIgnore: "괜찮아요",
    sameRoomMutedNote: "이 기기는 화면 전용입니다 (소리 꺼짐)",
    speakerOnlyMutedNote: "하울링이 나서 이 기기 소리만 껐어요 — 마이크는 켜져 있어 말은 그대로 됩니다",
    newBelow: "새 소식",
    sameLineNote: "같은 사무실에서 이미 접속한 기기가 있어 하울링을 막으려고 이 기기 소리를 껐어요",
    sameRoomUndo: "소리 다시 켜기",
    myLangHint: "이 언어로 말하고 듣습니다. 상대의 말이 이 언어로 통역돼요. (화면 언어는 안 바뀝니다)",
    langFromLabel: "번역할 언어 (내가 말하는 언어)",
    langToLabel: "번역될 언어 (상대방에게 보이는 자막)",
    langSwap: "언어 방향 바꾸기",
    langChangeTitle: "번역 언어 설정",
    done: "확인",
    sttListening: "음성 인식 중",
    sttProcessing: "자막 생성 중…",
    // 녹화 (기본 꺼짐 — 스위치를 켜야 보인다)
    recordingNotice: "녹화 중",
    recordLabel: "녹화",
    recordStart: "녹화 시작 — 참가자 전원에게 「녹화 중」이 표시됩니다",
    recordStop: "녹화 중지",
    recordingFailed: "녹화를 시작하지 못했습니다",
    listenStale: "자막이 안 잡혀요 — 화면을 한 번 탭해 주세요",
    emptyActiveHint1: "말하면 자막이 표시됩니다.",
    emptyActiveHint2: "음성이 안 되면 아래 입력칸에 쓰고 번역 버튼을 누르세요.",
    inAppNotice: "앱 안 브라우저에서는 영상·음성이 제한될 수 있어요.",
    openExternal: "브라우저에서 열기",
    linkCopied: "링크 복사됨 — 브라우저 주소창에 붙여넣으세요.",
    openExternalGuide: "버튼이 안 먹으면 아래 「링크 복사」를 누른 뒤, 크롬 등 브라우저를 직접 열고 주소창에 붙여넣어 입장하세요.",
    copyLinkBtn: "링크 복사",
    attachFile: "자료 첨부",
    sharedFiles: "공유 자료",
    newSharedDoc: "새 자료가 도착했어요",
    openNewTab: "새 탭에서 열기",
    docFormatsHint: "PDF·사진 (HWP는 PDF로 변환 후 업로드)",
    uploadingFile: "업로드 중...",
    uploadFailed: "업로드 실패",
    sendFailed: "전송 실패 — 잠시 후 다시 시도해주세요.",
    you: "You",
    translationActive: "실시간 번역 활성",
    translatingNow: "번역 중...",
    // Toasts
    translationStopped: "실시간 번역 종료",
    translationStartedPrefix: "실시간 번역 시작",
    admissionApproved: "입장 승인됨",
    admissionRejectedToast: "입장 거절됨",
    decideFailed: "처리 실패",
    authError: "인증 오류. 다시 로그인하세요.",
    sessionNotFoundToast: "상담 세션을 찾을 수 없습니다.",
    loadFailed: "상담 정보 로드 실패",
    doctorApprovedEntry: "의료진이 입장을 승인했습니다",
    entryRejected: "입장이 거절되었습니다",
    endConfirm: "상담을 종료하시겠습니까?",
    consultEnded: "상담이 종료되었습니다.",
    endFailed: "상담 종료 실패",
  },
  en: {
    aiSubtitleDisclaimer: "AI subtitles are for reference only. Confirm any medical judgment directly with your medical team.",
    guestTitle: "healwith Remote Consultation",
    guestLede: "You are joining via an invite link. Enter your name and allow camera/microphone access.",
    nameLabel: "Name (shown to the medical team)",
    namePlaceholder: "e.g. Айжан Нурланова / Ji-hoon Park",
    joining: "Connecting…",
    startConsult: "Start consultation",
    enterNameHint: "Enter your name to join.",
    guestSecurity1: "🔒 Communication is AES-256 encrypted. This link is for this consultation only — please don't forward it.",
    guestSecurity2: "If recording is needed, the medical team will inform you in advance.",
    nameTooShort: "Please enter a name of at least 2 characters.",
    inviteExpired: "The invite link has expired or is invalid. Please ask the administrator for a new link.",
    consultClosed: "This consultation has already ended.",
    rateLimited: "Too many attempts were detected and you were blocked. Please try again shortly.",
    connectFailed: "Connection failed",
    networkError: "Network error. Please try again shortly.",
    connecting: "Connecting to consultation...",
    sessionNotFound: "Consultation session not found.",
    linkMissingInvite: "This link has no entry pass. Please ask the sender for a new invite link.",
    goBack: "Go back",
    sessionPre: "Pre-consultation",
    sessionFollowUp: "Follow-up care",
    sessionEmergency: "Emergency consultation",
    sessionDiagnostic: "Diagnostic review",
    consultationFallback: "Consultation",
    connected: "Connected",
    reconnecting: "Connection unstable — reconnecting…",
    tapToEnableAudio: "🔊 Tap to enable sound",
    retryLabel: "Try again",
    noMediaNotice: "No camera or mic on this device. You'll join in listen-only mode.",
    mediaDeniedToast: "Camera/mic is blocked. Set it to 'Allow' via the lock icon in the address bar (or aA on phone), then reload.",
    connectStuck: "Couldn't connect. Check your internet and try again.",
    retryConnect: "Reconnect",
    connectNetworkTip: "Office or institutional networks often block video calls. Try a different network, such as your phone's hotspot, and retry.",
    preflightChecking: "Checking whether video calls work on this network…",
    preflightOk: "✅ This network supports the call — check your camera and mic in the preview above.",
    takenOverTitle: "Joined from another place",
    takenOverBody: "This screen was disconnected because you joined again from another tab or device. The call continues on the new screen.",
    takenOverRejoin: "Rejoin on this screen",
    micOffWarn: "Your mic isn't on — others can't hear you right now.",
    micRetry: "Turn on mic",
    waitingForOthers: "Waiting for others to join…",
    stillThereTitle: "Are you still there?",
    stillThereBody: "You'll be disconnected shortly. Tap the button below to stay.",
    stillThereYes: "Yes, I'm here",
    idleClosedTitle: "You've been disconnected",
    idleClosedBody: "It looked like you stepped away, so we closed the connection only. Your consultation is unchanged — rejoin any time.",
    idleRejoin: "Rejoin",
    cameraPreviewHint: "Check your camera and microphone before joining.",
    tabChat: "Chat",
    tabTranslation: "Translation",
    cameraBlocked: "Camera/microphone permission is blocked. Allow it from the lock icon in your browser's address bar.",
    micMutedWarning: "Your microphone is off — turn it on if you're speaking",
    unpinLabel: "Unpin",
    stopTranslation: "Stop translation",
    startTranslation: "Start live translation",
    interpretation: "Interpret",
    captionsLabel: "Subtitles",
    voiceLabel: "Voice",
    voiceNotReady: "Voice interpretation is not active yet (subtitles are available)",
    voiceOnMsg: "Voice interpretation on — you'll hear an interpreted voice",
    voiceOnPendingMsg: "Voice interpretation on — you'll hear it once the interpreter bot joins",
    voiceUnavailableMsg: "Voice interpretation is not available yet — captions still work",
    // 통역봇이 «연결이 계속 실패한다»고 알릴 때 (2026-08-28 신설).
    // 예전엔 아무 표시가 없어 사용자가 「켜졌는데 왜 안 나오지」로 계속 기다렸다.
    voiceFailingMsg: "Interpretation connection lost — reconnecting. Captions still work",
    voiceOffMsg: "Voice interpretation off — you'll hear the original voice",
    captionsOn: "Turn on subtitles",
    captionsOff: "Turn off subtitles",
    ctrlMic: "Mic",
    ctrlCam: "Camera",
    ctrlShare: "Share",
    ctrlChat: "Chat",
    ctrlLang: "Language",
    ttsOff: "Turn off voice output",
    ttsOn: "Turn on voice output",
    subtitleSizeTitle: "Subtitle size",
    subtitleSmall: "Subtitle S",
    subtitleMedium: "Subtitle M",
    subtitleLarge: "Subtitle L",
    endCall: "End",
    admissionRejectedTitle: "Entry was declined",
    admissionRejectedBody: "The medical team declined your entry. Please contact the administrator or coordinator.",
    waitingRoomTitle: "Waiting Room",
    waitingRoomBody1: "The medical team will approve your entry shortly.",
    waitingRoomBody2: "Please wait a moment — this screen will switch automatically.",
    checkingStatus: "Checking status...",
    waitingRoomPrivacy1: "This is a privacy-protected waiting room compliant with HIPAA / PIPA.",
    waitingRoomPrivacy2: "Your camera / microphone will not be activated until the consultation begins.",
    pendingWaiting: "Waiting to enter",
    anonymous: "Anonymous",
    approve: "Approve",
    reject: "Decline",
    doctorTile: "Doctor",
    patientTile: "Patient",
    roleDoctor: "Doctor",
    rolePatient: "Patient",
    roleCoordinator: "Coordinator",
    roleInterpreter: "Interpreter",
    roleGuest: "Guest",
    speakerUnknown: "Unknown speaker",
    waiting: "Waiting...",
    myScreen: "My view",
    livekitDisabled: "LiveKit not configured — video connection is disabled. Chat and interpretation are available.",
    chatEmpty: "Consultation messages will appear here.",
    messagePlaceholder: "Type a message...",
    translationEmpty1: "Press the [Interpret] button above",
    translationEmpty2: "to start live translation.",
    sttUnsupported1: "This browser does not support speech recognition.",
    sttUnsupported2: "No voice? Type below to translate instead.",
    manualPlaceholder: "Type text to translate...",
    manualHint: "No microphone? You can type to translate instead.",
    togglePanel: "Show/hide chat & translation",
    sttFailedNotice: "Voice recognition doesn't work in this browser. Type below to translate.",
    myLangLabel: "My language",
    langMineLabel: "My language",
    langMineHint: "You speak and hear in this language — others' speech is translated into it.",
    langPartnerNote: "The other side receives it in the language they chose —",
    sameRoomTitle: "Another device seems to be in the same room",
    sameRoomBody: "The two devices' speakers and mics are feeding back into each other. Making this one screen-only fixes it.",
    sameRoomAction: "Mute this device",
    sameRoomIgnore: "Dismiss",
    sameRoomMutedNote: "This device is screen-only (audio off)",
    speakerOnlyMutedNote: "Feedback detected — muted this device's speaker only. Your mic is still on, so you can keep talking.",
    newBelow: "New",
    sameLineNote: "Another device on the same network is already in this call — audio here is off to prevent feedback",
    sameRoomUndo: "Turn audio back on",
    myLangHint: "You speak and hear in this language — others' speech is translated into it. (This does not change the page language.)",
    langFromLabel: "Translate from (the language I speak)",
    langToLabel: "Translate to (subtitles the other side sees)",
    langSwap: "Swap direction",
    langChangeTitle: "Translation languages",
    done: "Done",
    sttListening: "Listening",
    sttProcessing: "Creating subtitles…",
    recordingNotice: "Recording",
    recordLabel: "Record",
    recordStart: "Start recording — everyone in the room will see a \"Recording\" badge",
    recordStop: "Stop recording",
    recordingFailed: "Could not start the recording",
    listenStale: "Subtitles aren't picking up — tap the screen once",
    emptyActiveHint1: "Speak and subtitles will appear.",
    emptyActiveHint2: "If voice doesn't work, type below and press the translate button.",
    inAppNotice: "In-app browsers may limit video and audio.",
    openExternal: "Open in browser",
    linkCopied: "Link copied — paste it into your browser.",
    openExternalGuide: "If nothing happens, tap 'Copy link' below, then open Chrome (or any browser) and paste it into the address bar to join.",
    copyLinkBtn: "Copy link",
    attachFile: "Attach file",
    sharedFiles: "Shared files",
    newSharedDoc: "New file shared",
    openNewTab: "Open in new tab",
    docFormatsHint: "PDF·images (convert HWP to PDF first)",
    uploadingFile: "Uploading...",
    uploadFailed: "Upload failed",
    sendFailed: "Send failed — please try again.",
    you: "You",
    translationActive: "Live translation active",
    translatingNow: "Translating...",
    translationStopped: "Live translation stopped",
    translationStartedPrefix: "Live translation started",
    admissionApproved: "Entry approved",
    admissionRejectedToast: "Entry declined",
    decideFailed: "Action failed",
    authError: "Authentication error. Please log in again.",
    sessionNotFoundToast: "Consultation session not found.",
    loadFailed: "Failed to load consultation info",
    doctorApprovedEntry: "The medical team approved your entry",
    entryRejected: "Your entry was declined",
    endConfirm: "Are you sure you want to end the consultation?",
    consultEnded: "The consultation has ended.",
    endFailed: "Failed to end consultation",
  },
  ru: {
    aiSubtitleDisclaimer: "Субтитры ИИ носят справочный характер. Любые медицинские решения уточняйте напрямую у врача.",
    guestTitle: "Удалённая консультация healwith",
    guestLede: "Вы входите по ссылке-приглашению. Введите своё имя и разрешите доступ к камере и микрофону.",
    nameLabel: "Имя (отображается медицинскому персоналу)",
    namePlaceholder: "напр.: Айжан Нурланова / Ji-hoon Park",
    joining: "Подключение…",
    startConsult: "Начать консультацию",
    enterNameHint: "Введите имя, чтобы войти.",
    guestSecurity1: "🔒 Связь зашифрована по стандарту AES-256. Эта ссылка предназначена только для этой консультации — не пересылайте её.",
    guestSecurity2: "Если потребуется запись, медицинский персонал предупредит вас заранее.",
    nameTooShort: "Введите имя длиной не менее 2 символов.",
    inviteExpired: "Ссылка-приглашение истекла или недействительна. Запросите новую ссылку у администратора.",
    consultClosed: "Эта консультация уже завершена.",
    rateLimited: "Обнаружено слишком много попыток, доступ заблокирован. Повторите попытку позже.",
    connectFailed: "Не удалось подключиться",
    networkError: "Ошибка сети. Повторите попытку позже.",
    connecting: "Подключение к консультации...",
    sessionNotFound: "Сессия консультации не найдена.",
    linkMissingInvite: "В этой ссылке нет пропуска для входа. Попросите отправителя прислать новую пригласительную ссылку.",
    goBack: "Назад",
    sessionPre: "Предварительная консультация",
    sessionFollowUp: "Последующее наблюдение",
    sessionEmergency: "Срочная консультация",
    sessionDiagnostic: "Анализ диагностики",
    consultationFallback: "Консультация",
    connected: "Подключено",
    reconnecting: "Нестабильное соединение — переподключение…",
    tapToEnableAudio: "🔊 Нажмите, чтобы включить звук",
    retryLabel: "Повторить",
    noMediaNotice: "На этом устройстве нет камеры и микрофона. Вы присоединитесь только для просмотра.",
    mediaDeniedToast: "Доступ к камере/микрофону заблокирован. Разрешите его через значок замка в адресной строке и обновите страницу.",
    connectStuck: "Не удалось подключиться. Проверьте интернет и повторите попытку.",
    retryConnect: "Переподключиться",
    connectNetworkTip: "Корпоративные сети часто блокируют видеосвязь. Попробуйте другую сеть — например, точку доступа телефона — и повторите попытку.",
    preflightChecking: "Проверяем, работает ли видеосвязь в этой сети…",
    preflightOk: "✅ Эта сеть поддерживает звонок — проверьте камеру и микрофон в окне выше.",
    takenOverTitle: "Выполнен вход в другом месте",
    takenOverBody: "Это окно отключено, потому что вы снова вошли с другой вкладки или устройства. Звонок продолжается в новом окне.",
    takenOverRejoin: "Войти заново в этом окне",
    micOffWarn: "Микрофон выключен — вас сейчас не слышат.",
    micRetry: "Включить микрофон",
    waitingForOthers: "Ожидание других участников…",
    stillThereTitle: "Вы ещё здесь?",
    stillThereBody: "Скоро соединение будет разорвано. Нажмите кнопку ниже, чтобы остаться.",
    stillThereYes: "Да, я здесь",
    idleClosedTitle: "Соединение разорвано",
    idleClosedBody: "Похоже, вы отошли, поэтому мы разорвали только соединение. Консультация сохранена — вы можете вернуться в любой момент.",
    idleRejoin: "Войти снова",
    cameraPreviewHint: "Проверьте камеру и микрофон перед входом.",
    tabChat: "Чат",
    tabTranslation: "Перевод",
    cameraBlocked: "Доступ к камере/микрофону заблокирован. Разрешите его, нажав на значок замка в адресной строке браузера.",
    micMutedWarning: "Микрофон выключен — включите его, если говорите",
    unpinLabel: "Открепить",
    stopTranslation: "Остановить перевод",
    startTranslation: "Начать перевод в реальном времени",
    interpretation: "Перевод",
    captionsLabel: "Субтитры",
    voiceLabel: "Озвучка",
    voiceNotReady: "Голосовой перевод пока не включён (субтитры доступны)",
    voiceOnMsg: "Голосовой перевод включён — вы услышите переведённый голос",
    voiceOnPendingMsg: "Голосовой перевод включён — вы услышите его, когда подключится бот-переводчик",
    voiceUnavailableMsg: "Голосовой перевод пока недоступен — субтитры работают",
    // 통역봇이 «연결이 계속 실패한다»고 알릴 때 (2026-08-28 신설).
    // 예전엔 아무 표시가 없어 사용자가 「켜졌는데 왜 안 나오지」로 계속 기다렸다.
    voiceFailingMsg: "Связь с переводом прервана — переподключаемся. Субтитры работают",
    voiceOffMsg: "Голосовой перевод выключен — вы слышите оригинальный голос",
    captionsOn: "Включить субтитры",
    captionsOff: "Выключить субтитры",
    ctrlMic: "Микрофон",
    ctrlCam: "Камера",
    ctrlShare: "Экран",
    ctrlChat: "Чат",
    ctrlLang: "Язык",
    ttsOff: "Выключить озвучивание",
    ttsOn: "Включить озвучивание",
    subtitleSizeTitle: "Размер субтитров",
    subtitleSmall: "Субтитры S",
    subtitleMedium: "Субтитры M",
    subtitleLarge: "Субтитры L",
    endCall: "Завершить",
    admissionRejectedTitle: "Вход отклонён",
    admissionRejectedBody: "Медицинский персонал отклонил ваш вход. Обратитесь к администратору или координатору.",
    waitingRoomTitle: "Комната ожидания",
    waitingRoomBody1: "Медицинский персонал скоро подтвердит ваш вход.",
    waitingRoomBody2: "Пожалуйста, подождите — этот экран переключится автоматически.",
    checkingStatus: "Проверка статуса...",
    waitingRoomPrivacy1: "Эта комната ожидания защищает конфиденциальность согласно стандартам HIPAA / PIPA.",
    waitingRoomPrivacy2: "Камера и микрофон не активируются до начала консультации.",
    pendingWaiting: "Ожидают входа",
    anonymous: "Аноним",
    approve: "Принять",
    reject: "Отклонить",
    doctorTile: "Врач",
    patientTile: "Пациент",
    roleDoctor: "Врач",
    rolePatient: "Пациент",
    roleCoordinator: "Координатор",
    roleInterpreter: "Переводчик",
    roleGuest: "Участник",
    speakerUnknown: "Неизвестный говорящий",
    waiting: "Ожидание...",
    myScreen: "Моё изображение",
    livekitDisabled: "LiveKit не настроен — видеосвязь отключена. Чат и перевод доступны.",
    chatEmpty: "Здесь будут отображаться сообщения консультации.",
    messagePlaceholder: "Введите сообщение...",
    translationEmpty1: "Нажмите кнопку [Перевод] вверху,",
    translationEmpty2: "чтобы начать перевод в реальном времени.",
    sttUnsupported1: "Этот браузер не поддерживает распознавание речи.",
    sttUnsupported2: "Нет голоса? Введите текст ниже для перевода.",
    manualPlaceholder: "Введите текст для перевода...",
    manualHint: "Нет микрофона? Можно ввести текст для перевода.",
    togglePanel: "Показать/скрыть чат и перевод",
    sttFailedNotice: "Распознавание речи не работает в этом браузере. Введите текст ниже.",
    myLangLabel: "Мой язык",
    langMineLabel: "Мой язык",
    langMineHint: "Вы говорите и слушаете на этом языке — речь собеседника переводится на него.",
    langPartnerNote: "Собеседник получит перевод на выбранный им язык —",
    sameRoomTitle: "Похоже, рядом есть второе устройство",
    sameRoomBody: "Динамики и микрофоны двух устройств создают эхо. Отключите звук на этом — и оно исчезнет.",
    sameRoomAction: "Отключить звук здесь",
    sameRoomIgnore: "Не сейчас",
    sameRoomMutedNote: "Это устройство — только экран (звук выключен)",
    speakerOnlyMutedNote: "Возник свист — отключили только динамик этого устройства. Микрофон включён, говорить можно.",
    newBelow: "Новые",
    sameLineNote: "В этой встрече уже есть устройство в той же сети — звук здесь выключен, чтобы не было эха",
    sameRoomUndo: "Включить звук",
    myLangHint: "Вы говорите и слушаете на этом языке — речь собеседника переводится на него. (Язык страницы не меняется.)",
    langFromLabel: "Переводить с (язык, на котором я говорю)",
    langToLabel: "Переводить на (субтитры для собеседника)",
    langSwap: "Поменять направление",
    langChangeTitle: "Языки перевода",
    done: "Готово",
    sttListening: "Слушаю",
    sttProcessing: "Создание субтитров…",
    recordingNotice: "Идёт запись",
    recordLabel: "Запись",
    recordStart: "Начать запись — все участники увидят значок «Идёт запись»",
    recordStop: "Остановить запись",
    recordingFailed: "Не удалось начать запись",
    listenStale: "Субтитры не распознаются — коснитесь экрана",
    emptyActiveHint1: "Говорите — появятся субтитры.",
    emptyActiveHint2: "Если голос не работает, введите текст ниже и нажмите кнопку перевода.",
    inAppNotice: "Встроенные браузеры приложений могут ограничивать видео и звук.",
    openExternal: "Открыть в браузере",
    linkCopied: "Ссылка скопирована — вставьте её в браузер.",
    openExternalGuide: "Если ничего не произошло, нажмите «Скопировать ссылку» ниже, откройте Chrome (или другой браузер) и вставьте её в адресную строку.",
    copyLinkBtn: "Скопировать ссылку",
    attachFile: "Прикрепить файл",
    sharedFiles: "Общие файлы",
    newSharedDoc: "Получен новый файл",
    openNewTab: "Открыть в новой вкладке",
    docFormatsHint: "PDF·фото (HWP конвертируйте в PDF)",
    uploadingFile: "Загрузка...",
    uploadFailed: "Ошибка загрузки",
    sendFailed: "Не удалось отправить — попробуйте ещё раз.",
    you: "Вы",
    translationActive: "Перевод в реальном времени активен",
    translatingNow: "Перевод...",
    translationStopped: "Перевод в реальном времени остановлен",
    translationStartedPrefix: "Перевод в реальном времени начат",
    admissionApproved: "Вход подтверждён",
    admissionRejectedToast: "Вход отклонён",
    decideFailed: "Не удалось выполнить действие",
    authError: "Ошибка авторизации. Войдите снова.",
    sessionNotFoundToast: "Сессия консультации не найдена.",
    loadFailed: "Не удалось загрузить данные консультации",
    doctorApprovedEntry: "Медицинский персонал подтвердил ваш вход",
    entryRejected: "Ваш вход отклонён",
    endConfirm: "Вы уверены, что хотите завершить консультацию?",
    consultEnded: "Консультация завершена.",
    endFailed: "Не удалось завершить консультацию",
  },
  kz: {
    aiSubtitleDisclaimer: "ЖИ субтитрлері тек анықтама үшін. Кез келген медициналық шешімді дәрігермен тікелей нақтылаңыз.",
    guestTitle: "healwith қашықтан консультациясы",
    guestLede: "Сіз шақыру сілтемесі арқылы кіресіз. Атыңызды енгізіп, камера/микрофонға рұқсат беріңіз.",
    nameLabel: "Аты-жөні (медициналық қызметкерге көрсетіледі)",
    namePlaceholder: "мыс.: Айжан Нұрланова / Ji-hoon Park",
    joining: "Қосылуда…",
    startConsult: "Консультацияны бастау",
    enterNameHint: "Кіру үшін атыңызды енгізіңіз.",
    guestSecurity1: "🔒 Байланыс AES-256 стандартымен шифрланады. Бұл сілтеме тек осы консультацияға арналған — басқаларға жібермеңіз.",
    guestSecurity2: "Жазу қажет болса, медициналық қызметкер алдын ала хабарлайды.",
    nameTooShort: "Кемінде 2 таңбадан тұратын атты енгізіңіз.",
    inviteExpired: "Шақыру сілтемесінің мерзімі өтті немесе жарамсыз. Әкімшіден жаңа сілтеме сұраңыз.",
    consultClosed: "Бұл консультация әлдеқашан аяқталды.",
    rateLimited: "Тым көп әрекет анықталып, бұғатталдыңыз. Біраздан кейін қайталап көріңіз.",
    connectFailed: "Қосылу сәтсіз аяқталды",
    networkError: "Желі қатесі. Біраздан кейін қайталап көріңіз.",
    connecting: "Консультацияға қосылуда...",
    sessionNotFound: "Консультация сессиясы табылмады.",
    linkMissingInvite: "Бұл сілтемеде кіру рұқсаты жоқ. Жіберушіден жаңа шақыру сілтемесін сұраңыз.",
    goBack: "Артқа",
    sessionPre: "Алдын ала консультация",
    sessionFollowUp: "Кейінгі бақылау",
    sessionEmergency: "Шұғыл консультация",
    sessionDiagnostic: "Диагностиканы қарау",
    consultationFallback: "Консультация",
    connected: "Қосылды",
    reconnecting: "Байланыс тұрақсыз — қайта қосылуда…",
    tapToEnableAudio: "🔊 Дыбысты қосу үшін түртіңіз",
    retryLabel: "Қайталау",
    noMediaNotice: "Бұл құрылғыда камера мен микрофон жоқ. Тек көру режимінде қосыласыз.",
    mediaDeniedToast: "Камера/микрофонға рұқсат бұғатталған. Мекенжай жолағындағы құлып белгісінен «Рұқсат ету» қойып, бетті жаңартыңыз.",
    connectStuck: "Қосылу мүмкін болмады. Интернетті тексеріп, қайталап көріңіз.",
    retryConnect: "Қайта қосылу",
    connectNetworkTip: "Кеңсе не мекеме желілері бейнеқоңырауды жиі бөгейді. Телефонның хотспоты сияқты басқа желіге ауысып, қайта көріңіз.",
    preflightChecking: "Бұл желіде бейнеқоңырау жұмыс істей ме, тексерілуде…",
    preflightOk: "✅ Бұл желі қоңырауды қолдайды — камера мен микрофонды жоғарыдан тексеріңіз.",
    takenOverTitle: "Басқа жерден кірдіңіз",
    takenOverBody: "Басқа қойынды не құрылғыдан қайта кіргендіктен, бұл терезенің қосылымы аяқталды. Қоңырау жаңа терезеде жалғасады.",
    takenOverRejoin: "Осы терезеде қайта кіру",
    micOffWarn: "Микрофон қосылмаған — қазір сізді естімейді.",
    micRetry: "Микрофонды қосу",
    waitingForOthers: "Басқа қатысушыларды күтудеміз…",
    stillThereTitle: "Әлі осындасыз ба?",
    stillThereBody: "Жақын арада байланыс үзіледі. Қалу үшін төмендегі түймені басыңыз.",
    stillThereYes: "Иә, осындамын",
    idleClosedTitle: "Байланыс үзілді",
    idleClosedBody: "Сіз кетіп қалған сияқтысыз, сондықтан тек байланысты үздік. Консультация сол күйінде — кез келген уақытта қайта кіре аласыз.",
    idleRejoin: "Қайта кіру",
    cameraPreviewHint: "Кіру алдында камера мен микрофонды тексеріңіз.",
    tabChat: "Чат",
    tabTranslation: "Аударма",
    cameraBlocked: "Камера/микрофон рұқсаты бұғатталған. Браузердің мекенжай жолындағы құлып белгісінен рұқсат беріңіз.",
    micMutedWarning: "Микрофон өшірулі — сөйлеп тұрсаңыз, қосыңыз",
    unpinLabel: "Бекітуді алу",
    stopTranslation: "Аударманы тоқтату",
    startTranslation: "Нақты уақыттағы аударманы бастау",
    interpretation: "Аударма",
    captionsLabel: "Субтитрлер",
    voiceLabel: "Дауыс",
    voiceNotReady: "Дауыстық аударма әлі қосылмаған (субтитрлер қолжетімді)",
    voiceOnMsg: "Дауыстық аударма қосулы — аударылған дауысты естисіз",
    voiceOnPendingMsg: "Дауыстық аударма қосулы — аудармашы бот қосылғанда естисіз",
    voiceUnavailableMsg: "Дауыстық аударма әзірге қолжетімсіз — субтитрлер жұмыс істейді",
    // 통역봇이 «연결이 계속 실패한다»고 알릴 때 (2026-08-28 신설).
    // 예전엔 아무 표시가 없어 사용자가 「켜졌는데 왜 안 나오지」로 계속 기다렸다.
    voiceFailingMsg: "Аударма байланысы үзілді — қайта қосылудамыз. Субтитрлер жұмыс істейді",
    voiceOffMsg: "Дауыстық аударма өшірулі — түпнұсқа дауысты естисіз",
    captionsOn: "Субтитрлерді қосу",
    captionsOff: "Субтитрлерді өшіру",
    ctrlMic: "Микрофон",
    ctrlCam: "Камера",
    ctrlShare: "Экран",
    ctrlChat: "Чат",
    ctrlLang: "Тіл",
    ttsOff: "Дауыстап оқуды өшіру",
    ttsOn: "Дауыстап оқуды қосу",
    subtitleSizeTitle: "Субтитр өлшемі",
    subtitleSmall: "Субтитр S",
    subtitleMedium: "Субтитр M",
    subtitleLarge: "Субтитр L",
    endCall: "Аяқтау",
    admissionRejectedTitle: "Кіруге рұқсат берілмеді",
    admissionRejectedBody: "Медициналық қызметкер кіруіңізден бас тартты. Әкімшіге немесе координаторға хабарласыңыз.",
    waitingRoomTitle: "Күту бөлмесі",
    waitingRoomBody1: "Медициналық қызметкер жақын арада кіруіңізді растайды.",
    waitingRoomBody2: "Сәл күте тұрыңыз — бұл экран автоматты түрде ауысады.",
    checkingStatus: "Күй тексерілуде...",
    waitingRoomPrivacy1: "Бұл күту бөлмесі HIPAA / PIPA стандарттарына сай құпиялылықты қорғайды.",
    waitingRoomPrivacy2: "Консультация басталғанға дейін камера / микрофон іске қосылмайды.",
    pendingWaiting: "Кіруді күтуде",
    anonymous: "Анонимді",
    approve: "Растау",
    reject: "Бас тарту",
    doctorTile: "Дәрігер",
    patientTile: "Науқас",
    roleDoctor: "Дәрігер",
    rolePatient: "Науқас",
    roleCoordinator: "Координатор",
    roleInterpreter: "Аудармашы",
    roleGuest: "Қатысушы",
    speakerUnknown: "Белгісіз сөйлеуші",
    waiting: "Күтуде...",
    myScreen: "Менің бейнем",
    livekitDisabled: "LiveKit бапталмаған — бейнебайланыс өшірілген. Чат пен аударма қолжетімді.",
    chatEmpty: "Консультация хабарламалары осында көрсетіледі.",
    messagePlaceholder: "Хабарлама енгізіңіз...",
    translationEmpty1: "Жоғарыдағы [Аударма] түймесін басып,",
    translationEmpty2: "нақты уақыттағы аударманы бастаңыз.",
    sttUnsupported1: "Бұл браузер сөзді тануды қолдамайды.",
    sttUnsupported2: "Дауыс жоқ па? Аудару үшін төменге мәтін теріңіз.",
    manualPlaceholder: "Аударылатын мәтінді енгізіңіз...",
    manualHint: "Микрофон жоқ па? Мәтінді теріп аударуға болады.",
    togglePanel: "Чат пен аударманы көрсету/жасыру",
    sttFailedNotice: "Бұл браузерде дауыс тану жұмыс істемейді. Төменге мәтін теріңіз.",
    myLangLabel: "Менің тілім",
    langMineLabel: "Менің тілім",
    langMineHint: "Осы тілде сөйлеп, тыңдайсыз — әңгімелесушінің сөзі осы тілге аударылады.",
    langPartnerNote: "Әңгімелесушіге өзі таңдаған тілде жеткізіледі —",
    sameRoomTitle: "Жақын жерде екінші құрылғы бар сияқты",
    sameRoomBody: "Екі құрылғының динамигі мен микрофоны жаңғырық тудырады. Осы құрылғының дыбысын өшірсеңіз жоғалады.",
    sameRoomAction: "Осы құрылғының дыбысын өшіру",
    sameRoomIgnore: "Қазір емес",
    sameRoomMutedNote: "Бұл құрылғы — тек экран (дыбыс өшірулі)",
    speakerOnlyMutedNote: "Ысқырық шықты — тек осы құрылғының динамигі өшірілді. Микрофон қосулы, сөйлей беріңіз.",
    newBelow: "Жаңа",
    sameLineNote: "Осы кездесуде бір желідегі басқа құрылғы бар — жаңғырықты болдырмау үшін дыбыс өшірілді",
    sameRoomUndo: "Дыбысты қосу",
    myLangHint: "Осы тілде сөйлеп, тыңдайсыз — әңгімелесушінің сөзі осы тілге аударылады. (Бет тілі өзгермейді.)",
    langFromLabel: "Аударылатын тіл (мен сөйлейтін тіл)",
    langToLabel: "Аударма тілі (әңгімелесушіге көрінетін субтитр)",
    langSwap: "Бағытты ауыстыру",
    langChangeTitle: "Аударма тілдері",
    done: "Дайын",
    sttListening: "Тыңдап тұр",
    sttProcessing: "Субтитр жасалуда…",
    recordingNotice: "Жазба жүріп жатыр",
    recordLabel: "Жазу",
    recordStart: "Жазуды бастау — барлық қатысушыға «Жазба жүріп жатыр» белгісі көрінеді",
    recordStop: "Жазуды тоқтату",
    recordingFailed: "Жазуды бастау мүмкін болмады",
    listenStale: "Субтитрлер танылмай тұр — экранды түртіңіз",
    emptyActiveHint1: "Сөйлесеңіз — субтитрлер шығады.",
    emptyActiveHint2: "Дауыс жұмыс істемесе, төменге теріп, аудару түймесін басыңыз.",
    inAppNotice: "Қолданба ішіндегі браузер видео мен дыбысты шектеуі мүмкін.",
    openExternal: "Браузерде ашу",
    linkCopied: "Сілтеме көшірілді — браузерге қойыңыз.",
    openExternalGuide: "Ештеңе болмаса, төмендегі «Сілтемені көшіру» түймесін басып, Chrome (немесе басқа браузерді) ашып, мекенжай жолағына қойып кіріңіз.",
    copyLinkBtn: "Сілтемені көшіру",
    attachFile: "Файл тіркеу",
    sharedFiles: "Ортақ файлдар",
    newSharedDoc: "Жаңа файл келді",
    openNewTab: "Жаңа қойындыда ашу",
    docFormatsHint: "PDF·фото (HWP-ні PDF-ке айналдырыңыз)",
    uploadingFile: "Жүктелуде...",
    uploadFailed: "Жүктеу сәтсіз",
    sendFailed: "Жіберілмеді — қайта көріңіз.",
    you: "Сіз",
    translationActive: "Нақты уақыттағы аударма белсенді",
    translatingNow: "Аударылуда...",
    translationStopped: "Нақты уақыттағы аударма тоқтатылды",
    translationStartedPrefix: "Нақты уақыттағы аударма басталды",
    admissionApproved: "Кіру расталды",
    admissionRejectedToast: "Кіруден бас тартылды",
    decideFailed: "Әрекет сәтсіз аяқталды",
    authError: "Аутентификация қатесі. Қайта кіріңіз.",
    sessionNotFoundToast: "Консультация сессиясы табылмады.",
    loadFailed: "Консультация деректерін жүктеу сәтсіз аяқталды",
    doctorApprovedEntry: "Медициналық қызметкер кіруіңізді растады",
    entryRejected: "Сіздің кіруіңізден бас тартылды",
    endConfirm: "Консультацияны аяқтағыңыз келе ме?",
    consultEnded: "Консультация аяқталды.",
    endFailed: "Консультацияны аяқтау сәтсіз аяқталды",
  },
  zh: {
    aiSubtitleDisclaimer: "AI 字幕仅供参考。任何医疗判断请直接向医疗团队确认。",
    guestTitle: "healwith 远程问诊",
    guestLede: "您正通过邀请链接进入。请输入您的姓名并允许使用摄像头/麦克风。",
    nameLabel: "姓名（向医疗团队显示）",
    namePlaceholder: "例如：Айжан Нурланова / Ji-hoon Park",
    joining: "连接中…",
    startConsult: "开始问诊",
    enterNameHint: "输入姓名即可进入。",
    guestSecurity1: "🔒 通信采用 AES-256 加密。此链接仅用于本次问诊，请勿转发他人。",
    guestSecurity2: "如需录制/录音，医疗团队将提前告知您。",
    nameTooShort: "请输入至少 2 个字符的姓名。",
    inviteExpired: "邀请链接已过期或无效。请向管理员索取新链接。",
    consultClosed: "本次问诊已结束。",
    rateLimited: "检测到过多尝试，您已被拦截。请稍后再试。",
    connectFailed: "连接失败",
    networkError: "网络错误。请稍后再试。",
    connecting: "正在连接问诊...",
    sessionNotFound: "未找到问诊会话。",
    linkMissingInvite: "此链接没有入场凭证。请向发送者索取新的邀请链接。",
    goBack: "返回",
    sessionPre: "诊前咨询",
    sessionFollowUp: "诊后随访",
    sessionEmergency: "紧急问诊",
    sessionDiagnostic: "诊断复核",
    consultationFallback: "问诊",
    connected: "已连接",
    reconnecting: "连接不稳定 — 正在重新连接…",
    tapToEnableAudio: "🔊 点按以开启声音",
    retryLabel: "重试",
    noMediaNotice: "此设备没有摄像头或麦克风。您将以仅收听模式加入。",
    mediaDeniedToast: "摄像头/麦克风被禁用。请在地址栏锁形图标（手机为 aA）中改为“允许”，然后刷新。",
    connectStuck: "连接失败。请检查网络后重试。",
    retryConnect: "重新连接",
    connectNetworkTip: "公司或机构网络经常拦截视频通话。请切换到其他网络（如手机热点）后重试。",
    preflightChecking: "正在检查此网络是否支持视频通话…",
    preflightOk: "✅ 此网络支持通话——请在上方预览中确认摄像头和麦克风。",
    takenOverTitle: "已在其他位置进入",
    takenOverBody: "由于您从其他标签页或设备重新进入，此窗口的连接已结束。通话将在新窗口继续。",
    takenOverRejoin: "在此窗口重新进入",
    micOffWarn: "麦克风未开启 — 对方现在听不到您。",
    micRetry: "开启麦克风",
    waitingForOthers: "正在等待对方加入…",
    stillThereTitle: "您还在吗？",
    stillThereBody: "连接即将断开。如果您还在，请点击下方按钮。",
    stillThereYes: "我还在",
    idleClosedTitle: "已断开连接",
    idleClosedBody: "看起来您暂时离开了，我们只断开了连接。咨询记录未受影响，您可以随时重新进入。",
    idleRejoin: "重新进入",
    cameraPreviewHint: "进入前请检查摄像头和麦克风。",
    tabChat: "聊天",
    tabTranslation: "翻译",
    cameraBlocked: "摄像头/麦克风权限被阻止。请在浏览器地址栏的锁形图标中允许。",
    micMutedWarning: "麦克风已关闭 — 如果您正在讲话请打开",
    unpinLabel: "取消固定",
    stopTranslation: "停止翻译",
    startTranslation: "开始实时翻译",
    interpretation: "口译",
    captionsLabel: "字幕",
    voiceLabel: "语音",
    voiceNotReady: "语音口译尚未开启（字幕可用）",
    voiceOnMsg: "语音口译已开启 — 您将听到翻译后的语音",
    voiceOnPendingMsg: "语音口译已开启 — 口译机器人加入后即可听到",
    voiceUnavailableMsg: "语音口译尚未开放 — 字幕仍可使用",
    // 통역봇이 «연결이 계속 실패한다»고 알릴 때 (2026-08-28 신설).
    // 예전엔 아무 표시가 없어 사용자가 「켜졌는데 왜 안 나오지」로 계속 기다렸다.
    voiceFailingMsg: "口译连接中断 — 正在重连。字幕仍可使用",
    voiceOffMsg: "语音口译已关闭 — 您将听到原声",
    captionsOn: "开启字幕",
    captionsOff: "关闭字幕",
    ctrlMic: "麦克风",
    ctrlCam: "摄像头",
    ctrlShare: "共享屏幕",
    ctrlChat: "聊天",
    ctrlLang: "语言",
    ttsOff: "关闭语音播报",
    ttsOn: "开启语音播报",
    subtitleSizeTitle: "字幕大小",
    subtitleSmall: "字幕 小",
    subtitleMedium: "字幕 中",
    subtitleLarge: "字幕 大",
    endCall: "结束",
    admissionRejectedTitle: "入室请求被拒绝",
    admissionRejectedBody: "医疗团队拒绝了您的入室请求。请联系管理员/协调员。",
    waitingRoomTitle: "候诊室",
    waitingRoomBody1: "医疗团队将很快批准您入室。",
    waitingRoomBody2: "请稍候——此页面将自动切换。",
    checkingStatus: "正在确认状态...",
    waitingRoomPrivacy1: "本候诊室符合 HIPAA / PIPA 隐私保护标准。",
    waitingRoomPrivacy2: "在问诊开始前，摄像头/麦克风不会被激活。",
    pendingWaiting: "等待入室",
    anonymous: "匿名",
    approve: "批准",
    reject: "拒绝",
    doctorTile: "医生",
    patientTile: "患者",
    roleDoctor: "医生",
    rolePatient: "患者",
    roleCoordinator: "协调员",
    roleInterpreter: "翻译",
    roleGuest: "参会者",
    speakerUnknown: "未知发言人",
    waiting: "等待中...",
    myScreen: "我的画面",
    livekitDisabled: "LiveKit 未配置——视频连接已禁用。聊天和口译仍可使用。",
    chatEmpty: "问诊消息将显示在此处。",
    messagePlaceholder: "输入消息...",
    translationEmpty1: "点击上方的 [口译] 按钮",
    translationEmpty2: "开始实时翻译。",
    sttUnsupported1: "此浏览器不支持语音识别。",
    sttUnsupported2: "无法语音？可在下方输入文字进行翻译。",
    manualPlaceholder: "输入要翻译的内容...",
    manualHint: "没有麦克风？可直接输入文字进行翻译。",
    togglePanel: "显示/隐藏聊天和翻译",
    sttFailedNotice: "此浏览器不支持语音识别。请在下方输入文字进行翻译。",
    myLangLabel: "我的语言",
    langMineLabel: "我的语言",
    langMineHint: "您用该语言说话和收听，对方的话会翻译成该语言。",
    langPartnerNote: "对方将收到其所选语言的字幕 —",
    sameRoomTitle: "附近似乎有另一台设备",
    sameRoomBody: "两台设备的扬声器和麦克风互相回授，产生啸叫。将本机设为仅显示画面即可解决。",
    sameRoomAction: "关闭本机声音",
    sameRoomIgnore: "暂不",
    sameRoomMutedNote: "本机为仅显示画面（声音已关闭）",
    speakerOnlyMutedNote: "检测到啸叫 — 仅关闭本机扬声器。麦克风仍开启，可以继续说话。",
    newBelow: "新消息",
    sameLineNote: "同一网络中已有设备加入本次通话 — 为避免啸叫，本机声音已关闭",
    sameRoomUndo: "重新开启声音",
    myLangHint: "您用该语言说话和收听，对方的话会翻译成该语言。（不会更改页面语言）",
    langFromLabel: "源语言（我说的语言）",
    langToLabel: "目标语言（对方看到的字幕）",
    langSwap: "交换方向",
    langChangeTitle: "翻译语言",
    done: "确定",
    sttListening: "正在聆听",
    sttProcessing: "正在生成字幕…",
    recordingNotice: "录制中",
    recordLabel: "录制",
    recordStart: "开始录制 — 房间内所有参与者都会看到「录制中」标识",
    recordStop: "停止录制",
    recordingFailed: "无法开始录制",
    listenStale: "字幕未能识别 — 请点一下屏幕",
    emptyActiveHint1: "说话即可显示字幕。",
    emptyActiveHint2: "如语音不可用，请在下方输入并点击翻译按钮。",
    inAppNotice: "应用内置浏览器可能限制视频和音频。",
    openExternal: "在浏览器中打开",
    linkCopied: "链接已复制——请粘贴到浏览器。",
    openExternalGuide: "如果没有反应，请点击下方「复制链接」，然后直接打开 Chrome 等浏览器，粘贴到地址栏进入。",
    copyLinkBtn: "复制链接",
    attachFile: "附加文件",
    sharedFiles: "共享资料",
    newSharedDoc: "收到新文件",
    openNewTab: "在新标签页打开",
    docFormatsHint: "PDF·图片 (HWP请先转为PDF)",
    uploadingFile: "上传中...",
    uploadFailed: "上传失败",
    sendFailed: "发送失败——请重试。",
    you: "您",
    translationActive: "实时翻译已启用",
    translatingNow: "翻译中...",
    translationStopped: "实时翻译已停止",
    translationStartedPrefix: "实时翻译已开始",
    admissionApproved: "已批准入室",
    admissionRejectedToast: "已拒绝入室",
    decideFailed: "操作失败",
    authError: "认证错误。请重新登录。",
    sessionNotFoundToast: "未找到问诊会话。",
    loadFailed: "加载问诊信息失败",
    doctorApprovedEntry: "医疗团队已批准您入室",
    entryRejected: "您的入室请求被拒绝",
    endConfirm: "确定要结束问诊吗？",
    consultEnded: "问诊已结束。",
    endFailed: "结束问诊失败",
  },
  ja: {
    aiSubtitleDisclaimer: "AI字幕は参考用です。医学的な判断は医療スタッフに直接ご確認ください。",
    guestTitle: "healwith オンライン診療",
    guestLede: "招待リンクから入室します。お名前を入力し、カメラ/マイクの使用を許可してください。",
    nameLabel: "お名前（医療スタッフに表示されます）",
    namePlaceholder: "例：Айжан Нурланова / Ji-hoon Park",
    joining: "接続中…",
    startConsult: "診療を開始",
    enterNameHint: "お名前を入力すると入室できます。",
    guestSecurity1: "🔒 通信はAES-256で暗号化されます。このリンクはこの診療専用です — 他の方に転送しないでください。",
    guestSecurity2: "録画/録音が必要な場合は、医療スタッフが事前にご案内します。",
    nameTooShort: "お名前を2文字以上入力してください。",
    inviteExpired: "招待リンクの有効期限が切れているか、無効です。管理者に新しいリンクをご依頼ください。",
    consultClosed: "この診療はすでに終了しています。",
    rateLimited: "試行回数が多すぎたためブロックされました。しばらくしてから再度お試しください。",
    connectFailed: "接続に失敗しました",
    networkError: "ネットワークエラー。しばらくしてから再度お試しください。",
    connecting: "診療に接続中...",
    sessionNotFound: "診療セッションが見つかりません。",
    linkMissingInvite: "このリンクには入室パスがありません。送信者に新しい招待リンクを依頼してください。",
    goBack: "戻る",
    sessionPre: "事前相談",
    sessionFollowUp: "事後ケア",
    sessionEmergency: "緊急相談",
    sessionDiagnostic: "診断レビュー",
    consultationFallback: "診療",
    connected: "接続済み",
    reconnecting: "接続が不安定です — 再接続中…",
    tapToEnableAudio: "🔊 タップして音声をオンにする",
    retryLabel: "再試行",
    noMediaNotice: "この端末にはカメラ・マイクがありません。視聴のみで参加します。",
    mediaDeniedToast: "カメラ・マイクがブロックされています。アドレスバーの鍵アイコン（スマホはaA）で「許可」に変えて再読み込みしてください。",
    connectStuck: "接続できませんでした。通信環境を確認して再度お試しください。",
    retryConnect: "再接続",
    connectNetworkTip: "会社や機関のネットワークはビデオ通話を遮断することがよくあります。スマホのテザリングなど別のネットワークに切り替えて、もう一度お試しください。",
    preflightChecking: "このネットワークでビデオ通話ができるか確認中…",
    preflightOk: "✅ このネットワークで通話できます — カメラとマイクは上のプレビューでご確認ください。",
    takenOverTitle: "別の場所から入室しました",
    takenOverBody: "別のタブや端末から再入室したため、この画面の接続は終了しました。通話は新しい画面で続いています。",
    takenOverRejoin: "この画面で再入室",
    micOffWarn: "マイクがオンになっていません — 今は相手に声が届きません。",
    micRetry: "マイクをオン",
    waitingForOthers: "相手の参加を待っています…",
    stillThereTitle: "まだいらっしゃいますか？",
    stillThereBody: "まもなく接続が切断されます。続ける場合は下のボタンを押してください。",
    stillThereYes: "はい、います",
    idleClosedTitle: "接続を切断しました",
    idleClosedBody: "席を外されたようなので接続のみ切断しました。相談はそのままですので、いつでも再入室できます。",
    idleRejoin: "再入室",
    cameraPreviewHint: "入室前にカメラとマイクを確認してください。",
    tabChat: "チャット",
    tabTranslation: "翻訳",
    cameraBlocked: "カメラ／マイクの許可がブロックされています。ブラウザのアドレスバーの鍵アイコンから許可してください。",
    micMutedWarning: "マイクがオフです — 話す場合はオンにしてください",
    unpinLabel: "固定解除",
    stopTranslation: "翻訳を停止",
    startTranslation: "リアルタイム翻訳を開始",
    interpretation: "通訳",
    captionsLabel: "字幕",
    voiceLabel: "音声",
    voiceNotReady: "音声通訳はまだ有効になっていません（字幕は利用可能）",
    voiceOnMsg: "音声通訳オン — 通訳された音声が聞こえます",
    voiceOnPendingMsg: "音声通訳オン — 通訳ボットが入室すると聞こえます",
    voiceUnavailableMsg: "音声通訳はまだ利用できません — 字幕は使えます",
    // 통역봇이 «연결이 계속 실패한다»고 알릴 때 (2026-08-28 신설).
    // 예전엔 아무 표시가 없어 사용자가 「켜졌는데 왜 안 나오지」로 계속 기다렸다.
    voiceFailingMsg: "通訳の接続が切れました — 再接続中です。字幕は使えます",
    voiceOffMsg: "音声通訳オフ — 元の音声が聞こえます",
    captionsOn: "字幕をオン",
    captionsOff: "字幕をオフ",
    ctrlMic: "マイク",
    ctrlCam: "カメラ",
    ctrlShare: "画面共有",
    ctrlChat: "チャット",
    ctrlLang: "言語",
    ttsOff: "音声出力をオフ",
    ttsOn: "音声出力をオン",
    subtitleSizeTitle: "字幕サイズ",
    subtitleSmall: "字幕 小",
    subtitleMedium: "字幕 中",
    subtitleLarge: "字幕 大",
    endCall: "終了",
    admissionRejectedTitle: "入室が拒否されました",
    admissionRejectedBody: "医療スタッフが入室を拒否しました。管理者/コーディネーターにお問い合わせください。",
    waitingRoomTitle: "待合室",
    waitingRoomBody1: "医療スタッフがまもなく入室を承認します。",
    waitingRoomBody2: "少々お待ちください — この画面は自動的に切り替わります。",
    checkingStatus: "状態を確認中...",
    waitingRoomPrivacy1: "この待合室はHIPAA / PIPA基準のプライバシー保護待合室です。",
    waitingRoomPrivacy2: "診療開始まで、カメラ/マイクは有効になりません。",
    pendingWaiting: "入室待ち",
    anonymous: "匿名",
    approve: "承認",
    reject: "拒否",
    doctorTile: "医師",
    patientTile: "患者",
    roleDoctor: "医師",
    rolePatient: "患者",
    roleCoordinator: "コーディネーター",
    roleInterpreter: "通訳",
    roleGuest: "参加者",
    speakerUnknown: "話者不明",
    waiting: "待機中...",
    myScreen: "自分の画面",
    livekitDisabled: "LiveKit未設定 — ビデオ接続が無効です。チャットと通訳はご利用いただけます。",
    chatEmpty: "診療メッセージがここに表示されます。",
    messagePlaceholder: "メッセージを入力してください...",
    translationEmpty1: "上部の[通訳]ボタンを押して",
    translationEmpty2: "リアルタイム翻訳を開始してください。",
    sttUnsupported1: "このブラウザは音声認識に対応していません。",
    sttUnsupported2: "音声が使えない場合は下に入力して翻訳できます。",
    manualPlaceholder: "翻訳する内容を入力...",
    manualHint: "マイクが使えない場合は入力して翻訳できます。",
    togglePanel: "チャット・翻訳の表示/非表示",
    sttFailedNotice: "このブラウザでは音声認識が使えません。下に入力して翻訳してください。",
    myLangLabel: "私の言語",
    langMineLabel: "私の言語",
    langMineHint: "この言語で話し、聞きます。相手の発言はこの言語に通訳されます。",
    langPartnerNote: "相手には相手が選んだ言語で届きます —",
    sameRoomTitle: "同じ部屋に別の端末があるようです",
    sameRoomBody: "2台のスピーカーとマイクが互いに反響してハウリングが起きています。この端末を画面のみにすると解消します。",
    sameRoomAction: "この端末の音を切る",
    sameRoomIgnore: "閉じる",
    sameRoomMutedNote: "この端末は画面のみ（音声オフ）",
    speakerOnlyMutedNote: "ハウリングのため、この端末のスピーカーのみ消音しました。マイクはオンなので発言できます。",
    newBelow: "新着",
    sameLineNote: "同じ回線の端末が既に参加中です — ハウリング防止のためこの端末の音声を切りました",
    sameRoomUndo: "音声を戻す",
    myLangHint: "この言語で話し、聞きます。相手の発言はこの言語に通訳されます。（画面の言語は変わりません）",
    langFromLabel: "翻訳元の言語（自分が話す言語）",
    langToLabel: "翻訳先の言語（相手に表示される字幕）",
    langSwap: "方向を入れ替え",
    langChangeTitle: "翻訳言語",
    done: "完了",
    sttListening: "音声認識中",
    sttProcessing: "字幕を生成中…",
    recordingNotice: "録画中",
    recordLabel: "録画",
    recordStart: "録画を開始 — 参加者全員に「録画中」と表示されます",
    recordStop: "録画を停止",
    recordingFailed: "録画を開始できませんでした",
    listenStale: "字幕が拾えていません — 画面を一度タップしてください",
    emptyActiveHint1: "話すと字幕が表示されます。",
    emptyActiveHint2: "音声が使えない場合は下に入力して翻訳ボタンを押してください。",
    inAppNotice: "アプリ内ブラウザでは映像・音声が制限される場合があります。",
    openExternal: "ブラウザで開く",
    linkCopied: "リンクをコピーしました — ブラウザに貼り付けてください。",
    openExternalGuide: "反応がない場合は、下の「リンクをコピー」を押し、Chrome などのブラウザを直接開いてアドレスバーに貼り付けて入室してください。",
    copyLinkBtn: "リンクをコピー",
    attachFile: "ファイル添付",
    sharedFiles: "共有資料",
    newSharedDoc: "新しい資料が届きました",
    openNewTab: "新しいタブで開く",
    docFormatsHint: "PDF·写真 (HWPはPDFに変換)",
    uploadingFile: "アップロード中...",
    uploadFailed: "アップロード失敗",
    sendFailed: "送信に失敗しました — もう一度お試しください。",
    you: "あなた",
    translationActive: "リアルタイム翻訳が有効",
    translatingNow: "翻訳中...",
    translationStopped: "リアルタイム翻訳を停止しました",
    translationStartedPrefix: "リアルタイム翻訳を開始しました",
    admissionApproved: "入室を承認しました",
    admissionRejectedToast: "入室を拒否しました",
    decideFailed: "処理に失敗しました",
    authError: "認証エラー。再度ログインしてください。",
    sessionNotFoundToast: "診療セッションが見つかりません。",
    loadFailed: "診療情報の読み込みに失敗しました",
    doctorApprovedEntry: "医療スタッフが入室を承認しました",
    entryRejected: "入室が拒否されました",
    endConfirm: "診療を終了しますか？",
    consultEnded: "診療が終了しました。",
    endFailed: "診療の終了に失敗しました",
  },
};
